### ISSUE TITLE
Make sure sepolicy gui works properly after rebase to 2.6.

### ISSUE THREAD

**Issue by vmojzis** [fedora-selinux/selinux#33]
Userspace v. 2.6 brought significant changes to sepolicy code (e.g. use of SETools 4) and sepolicy gui needs to reflect them. 
Corresponding upstream commits:
https://github.com/SELinuxProject/selinux/commit/041e00106f9a30d9e444f0b3403ec9204c0688d2
https://github.com/SELinuxProject/selinux/commit/31fcd66d39e2be5e94d07ee8c2445efdab6cf230
https://github.com/SELinuxProject/selinux/commit/8fe1b0ca27652cf6b7c588d2ff7792f8e942939f

**Comment by bachradsusi** [comment]
I believe this is already fixed.
